services:
  app:
    container_name: social_network_app
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: social_network_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
